name: Cypress Tests - In Class Project

on:
  push:
    branches:
      - main
    paths:
      - 'project-tests/**.js'
      - 'project-tests/**.json'
      - 'project-tests/**.yml'

jobs:
  project-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install
        working-directory: ./project-tests

      - name: Run Cypress tests
        run: npm run cypress:headless
        working-directory: ./project-tests